import { CButton, CCol, CContainer, CImage, CRow } from "@coreui/react";
import {
  faArrowCircleLeft,
  faArrowLeft,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import React from "react";
import { useHistory } from "react-router-dom";
import TransparentCard from "src/commons/cards/TransparentCard";
import { logo_png } from "src/iconsimport";
import FaqView from "./FaqView";

const Terms = () => {
  const history = useHistory();

  return (
    <CContainer>
      <CRow>
        <CCol lg={7} md={12} className="p-3">
          <TransparentCard className="p-3" title="Terms & Condition">
            {/* <h5 className="fw-bolder mt-3">TERMS & CONDITIONS</h5> */}
            <p>
              Infinite solution is a reliable and user-friendly online bill
              payment platform. User can pay their view bills online. On the
              Infinite solution website, the user can pay their bills across a
              variety of operators. The current bill payment via Infinite
              solution website can be done across all major areas like Delhi NCR
              and many others.
            </p>
            <p>
              This document is an electronic record in terms of Information
              Technology Act, 2000 and generated by a computer system and does
              not require any physical or digital signatures. This document is
              published in accordance with the provisions of Rule 3 of the
              Information Technology (Intermediaries guidelines) Rules, 2011
              that provide for the due diligence to be exercised by the Website.
            </p>
            <p>
              Infinite solution reserve the right to modify the Terms at any
              time without giving you any prior notice. Your use of the Website
              following any such modification constitutes your agreement to
              follow and be bound by the Terms as modified. You can accept the
              Terms by: Using the Website; or By actually using the Services. In
              this case, you understand and agree that Infinite solution will
              treat your use of the Services as acceptance of the Terms from
              that point onwards.
            </p>
            <p>
              By using the Website and its Services, you agree that you have
              read and understood these Terms and you agree to be bound by these
              Terms and use the Services in compliance with these Terms. Please
              read these Terms carefully. If you do not agree to be bound by (or
              cannot comply with) any of the terms below, please leave the
              Website immediately and terminate your account with us.
            </p>
            <p>
              It is important to note, however, that the timeliness and accuracy
              of any or all of the information is not guaranteed. Infinite
              solution.co.in does not guarantee the services/functions contained
              in the site will be uninterrupted or error-free, that this site or
              its server will be free of viruses or other harmful components or
              defects will be corrected even if Infinite solution.co.in is aware
              of them.
            </p>
            <p>
              Use of Services and Information on the website: In order to access
              certain Services, you may be required to provide information about
              yourself as part of the registration process for the Service, or
              as part of your continued use of the Services. You agree that any
              registration information you give to us will always be true,
              accurate, correct, complete and up to date.
            </p>
            <p>
              Any phone number used to register with the Website needs to be
              registered in your name. You agree that you are solely responsible
              for (and that Infinite solution has no responsibility to you or to
              any third party for) any breach of your obligations under the
              Terms and for the consequences (including any loss or damage which
              Infinite solution may suffer) of any such breach. All personal and
              contact information provided by you will be kept confidential by
              Infinite solution.
            </p>
            <p>
              {" "}
              This includes your personal information given in relation to your
              account creation and subsequent administration. You will notify
              Infinite solution upon coming across any objectionable content on
              the Website and Infinite solution shall use best efforts to remove
              such objectionable content within Forty-eight hours from being
              duly notified.
            </p>
            <p>
              Your Use of Information: All of the information available on or
              through the Services and/or the Website, including without
              limitation, text, photographs, graphics and video and audio
              content, is owned by Infinite solution and is protected by
              copyright, trademark, patent and trade secret laws and other
              proprietary rights and.
            </p>
            <p>
              You acknowledge that the Services and any underlying technology or
              software used in connection with the Services contain Infinite
              solution's proprietary information.
            </p>
            <p>
              Copyright and Trademark Unless otherwise noted, all materials on
              this site are protected as the copyrights, trademarks and/ or
              other intellectual properties owned by BillKaro.in Privacy and
              Intellectual Property Protection: Infinite solution Pay's Privacy
              Policy explains how we treat your personal data and protect your
              privacy when you use our Services.
            </p>
            <p>
              {" "}
              By using our services, you agree that Infinite solution can use
              such data in accordance with their policies. You agree and
              understand that you are responsible for maintaining the
              confidentiality of passwords associated with any account you use
              to access the Services.
            </p>
            <p>
              {" "}
              You agree that you will be solely responsible to Infinite solution
              for all activities that occur under your account.
            </p>
            <p>
              If you become aware of any unauthorized use of your password or of
              your account, you agree to notify us immediately at Infinite
              solution Helpdesk.
            </p>
            <p>
              {" "}
              No Warranties: Terms and conditions unless otherwise stated with
              respect to our products and/or services are offered on an “as is”
              basis without any warranty whatsoever either express or implied.
            </p>
            <p>
              {" "}
              Infinite solution disclaims all warranties whether express or
              implied, including but not limited to: That our website will
              always function without disruptions, delay or errors; Your ability
              to use the service through the website; Your satisfaction with the
              services or the website; Security and privacy of the data; That
              bugs or errors in the Service and/or Website will be corrected.
            </p>
          </TransparentCard>
        </CCol>
        <CCol lg={5} md={12} className="p-3">
          <FaqView />
        </CCol>
      </CRow>
      <CButton
        className="btn mb-5 p-3"
        style={{ width: 200, height: "auto" }}
        onClick={() => {
          history.push("/");
        }}
      >
        <FontAwesomeIcon className="me-3" icon={faArrowLeft}></FontAwesomeIcon>
        Back To Home
      </CButton>
    </CContainer>
  );
};

export default Terms;
